#!/bin/bash
#PBS -N wrf
#PBS -l ncpus=16
#PBS -l nodes=4:ppn=4

##cd /home/jwarner/WRF/WRFV2/test/em_b_wave
cd /home/jwarner/WRF/WRFV2/test/em_real

##mpirun -n 1 -hostfile $PBS_NODEFILE ./ideal.exe 
mpirun -n 16 -hostfile $PBS_NODEFILE ./wrf.exe 
