#!/bin/bash
### Job name
#PBS -N joe_tc
### Number of nodes
#PBS -l nodes=6:ppn=8,walltime=120:00:00
### Mail to user
#PBS -m ae
#PBS -M jcwarner@usgs.gov
### Out files
###PBS -e isabel_105.err
###PBS -o isabel_105.out
### PBS queue
#PBS -q standard

echo "this job is running on:"
cat $PBS_NODEFILE

NPROCS=`wc -l < $PBS_NODEFILE`

cd /raid2/jcwarner/Projects/JOE_TC/tests

/usr/local/mpi/bin/mpirun -np 44 -machinefile $PBS_NODEFILE ./oceanM Projects/JOE_TC/coupling_joe_tc.in > joe_tc.out
