#!/bin/bash
### Job name
#PBS -N cwstv3
### Number of nodes
#PBS -l nodes=1:ppn=8,walltime=120:00:00
### Mail to user
#PBS -m ae
#PBS -M jcwarner@usgs.gov
### Out files
###PBS -e isabel_105.err
###PBS -o isabel_105.out
### PBS queue
#PBS -q standard

umask 0002

echo "this job is running on:"
cat $PBS_NODEFILE

NPROCS=`wc -l < $PBS_NODEFILE`

cd /raid3/jcwarner/Projects/coawst_v3.1/coawst_v3.1_114/

###mpirun -np 2 -machinefile $PBS_NODEFILE ./coawstM Projects/JOE_TCd/coupling_joe_tc.in > joe_tc.out
mpirun -np 8 -machinefile $PBS_NODEFILE ./coawstM Projects/Sandy/coupling_sandy1.in > cwstv3.out
