#!/bin/bash
### Job name
#PBS -N joe_tc
### Number of nodes
#PBS -l nodes=1:ppn=8,walltime=120:00:00
### Mail to user
#PBS -m ae
#PBS -M jcwarner@usgs.gov
### Out files
###PBS -e isabel_105.err
###PBS -o isabel_105.out
### PBS queue
#PBS -q standard

umask 0002

echo "this job is running on:"
cat $PBS_NODEFILE

NPROCS=`wc -l < $PBS_NODEFILE`

cd /raid1/jcwarner/Models/COAWST_regress/20091202/

/usr/local/mpi/bin/mpirun -np 3 -machinefile $PBS_NODEFILE ./coawstM Projects/JOE_TCd/coupling_joe_tc.in > joe_tc.out
