#! /bin/bash

# Build and run the COAWST test case Projects/Inlet_test/Coupled

set -e

while getopts "gs" opt
do
  case "$opt" in
    g)
      use_debug=1
      ;;
    s)
      use_slurm=1
      ;;
    esac
done
shift $(( ${OPTIND}-1 ))


pwd=${PWD}
host=$(echo ${HOSTNAME} | cut -d "." -f 1)
platform=$(uname -s -m | tr " " "-")

# Collate and build model, creating to link to the executable
# in the current directory

build_cmd="roms_build -m"

if test -n "${use_debug}"
then
  build_cmd=${build_cmd}" -g"
fi

${build_cmd}

# Change the name of the link to "coawstM". (I will build this capability intol roms_build.)

mv oceanM coawstM

# Specify output file name

file=coawst
file=${file}-${host}-${platform}-${FORT}
if test -n "${use_debug}"
then
    file=${file}-debug
fi
if test -n "${use_slurm}"
then
    file=${file}-slurm
fi
file=${file}-$(date +%Y%m%d%H%M%S)
file_out=${file}.log
file_err=${file}.err

# Run the model...

if test -n "${use_slurm}"
then

  # ...with SLURM

  file_slurm=sbatch-$(date +%Y%m%d%H%M%S)

  cat > ${file_slurm} << EOF
#! /bin/bash
#SBATCH --partition=NeSI
#SBATCH --job-name=ROMS
#SBATCH --output=${file_out}
#SBATCH --error=${file_err}
#SBATCH --nodes=1
#SBATCH --ntasks=2
#SBATCH --time=02:00:00
#SBATCH --share
#SBATCH --hint=nomultithread
echo ROMS starting at \$(date +%Y-%m-%d\ %H:%M:%S\ %Z)
srun ./coawstM coupling_inlet_test.in
echo ROMS finished at \$(date +%Y-%m-%d\ %H:%M:%S\ %Z)
EOF

  sbatch ${file_slurm}

else

  # ...in current shell

  echo "Output will be saved in "${file_out}

  mpirun -np 2 ./coawstM coupling_inlet_test.in | tee ${file_out}


fi

