# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
import sphinx
from sphinx.util import logging
sys.path.insert(0, os.path.abspath('../physics'))
sys.path.insert(0, os.path.abspath('../tests'))


# -- Project information -----------------------------------------------------

project = 'Community Fire Behavior Model User\'s Guide'
copyright = '2024, '
author = ' '

# The short X.Y version
version = 'develop'
# The full version, including alpha/beta/rc tags
release = f'version {version}'
html_logo = "https://www.archives.ucar.edu/sites/default/files/images/NSF-NCAR_Lockup-UCAR-Dark_102523%20%282%29.png"

numfig = True

nitpick_ignore = [('py:class', 'obj'),('py:class', 
                   'yaml.dumper.Dumper'),('py:class', 
                   'xml.etree.ElementTree'),]

# -- General configuration ---------------------------------------------------

# Sphinx extension module names:
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.doctest',
    'sphinx.ext.intersphinx',
    'sphinx.ext.extlinks',
    'sphinx.ext.mathjax',
    'sphinxcontrib.bibtex',
]

bibtex_bibfiles = ['references.bib']
bibtex_reference_style = 'author_year'

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. 
# Not set because default is 'en'.
# language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build',
                    '.DS_Store',]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# Documentation-wide substitutions

rst_prolog = """
.. |wflow_env| replace:: ``srw_app``
.. |graphics_env| replace:: ``regional_workflow``
.. |cmaq_env| replace:: ``regional_workflow_cmaq``
.. |activate| replace:: ``conda activate srw_app``
.. |prompt| replace:: ``(srw_app)``
.. |latestr| replace:: v2.2.0
.. |branch| replace:: ``develop``
.. |data| replace:: develop
"""

# Linkcheck options

# Avoid a 403 Forbidden error when accessing certain links (e.g., noaa.gov)
user_agent = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"

# Ignore working links that cause a linkcheck 403 error.
#linkcheck_ignore = [r'https://www\.intel\.com/content/www/us/en/docs/cpp\-compiler/developer\-guide\-reference/2021\-10/thread\-affinity\-interface\.html',
#                    r'https://www\.intel\.com/content/www/us/en/developer/tools/oneapi/hpc\-toolkit\-download\.html',
#                    r'https://glossary.ametsoc.org/.*',
#                   ]


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'classic'
html_logo= "https://www.archives.ucar.edu/sites/default/files/images/NSF-NCAR_Lockup-UCAR-Dark_102523%20%282%29.png"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}
html_theme_options = {
    "body_max_width": "none", 
    "navigation_depth": 8,
    }


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'UFS-SRWeather-App'


# -- Options for LaTeX output ------------------------------------------------

latex_engine = 'pdflatex'
latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
      'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
      'pointsize': '11pt',

    # Additional stuff for the LaTeX preamble.
      'preamble': r'''
        \usepackage{charter}
        \usepackage[defaultsans]{lato}
        \usepackage{inconsolata}
    ''',
    # Release name prefix
      'releasename': ' ',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'CFBM-UsersGuide.tex', 'Community Fire Behavior Module Documentation',
     ' ', 'manual'),
]



# -- Options for Epub output -------------------------------------------------

# Bibliographic Dublin Core info.
epub_title = project

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#
# epub_identifier = ''

# A unique identification for the text.
#
# epub_uid = ''

# A list of files that should not be packed into the epub file.
epub_exclude_files = ['search.html']


# -- Extension configuration -------------------------------------------------


# -- Options for intersphinx extension ---------------------------------------

# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {
   'python': ('https://docs.python.org/3', None),
   'hpc-stack': ('https://hpc-stack-epic.readthedocs.io/en/develop/', None),
   'spack-stack': ('https://spack-stack.readthedocs.io/en/develop/', None),
   'met': ('https://met.readthedocs.io/en/develop/', None),
   'metplus': ('https://metplus.readthedocs.io/en/develop/', None),
   'ufs-wm': ('https://ufs-weather-model.readthedocs.io/en/develop/', None),
   'upp': ('https://upp.readthedocs.io/en/develop/', None),
   'ufs-utils': ('https://noaa-emcufs-utils.readthedocs.io/en/latest/', None),
   'ccpp-techdoc': ('https://ccpp-techdoc.readthedocs.io/en/ufs_srw_app_v2.2.0/', None),
   'stochphys': ('https://stochastic-physics.readthedocs.io/en/latest/', None),
   'srw_v2.2.0': ('https://ufs-srweather-app.readthedocs.io/en/release-public-v2.2.0/', None),
}

# -- Options for extlinks extension ---------------------------------------

extlinks_detect_hardcoded_links = True
extlinks = {'github-docs': ('https://docs.github.com/en/%s', '%s'),
            'nco': ('https://www.nco.ncep.noaa.gov/idsb/implementation_standards/%s', '%s'),
            "rst": ("https://www.sphinx-doc.org/en/master/usage/restructuredtext/%s", "%s"),
            "rtd": ("https://readthedocs.org/projects/ufs-srweather-app/%s", "%s"),
            'srw-repo': ('https://github.com/ufs-community/ufs-srweather-app/%s', '%s'),
            'srw-wiki': ('https://github.com/ufs-community/ufs-srweather-app/wiki/%s','%s'),
            'uw': ('https://uwtools.readthedocs.io/en/main/%s', '%s'),
            }

