build_table_qr_acr_qg – TEMPO Microphysics
build_table_qr_acr_qg Subroutine
58 statements
Source File
private subroutine build_table_qr_acr_qg(rank, num_proc)
Uses
module_mp_tempo_params
build lookup table data for rain-graupel collection
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: rank
integer, intent(in) :: num_proc
Calls
Called by
Call graph
build_table_qr_acr_qg calls mpi_allgather, mpi_barrier, mpi_wtime, gather, get_index_for_rank, initialize_arrays_qr_acr_qg, qr_acr_qg
gather calls mpi_gatherv
tempo_build_tables calls build_table_qr_acr_qg
build_tables calls tempo_build_tables