build_table_qr_acr_qs – TEMPO Microphysics
build_table_qr_acr_qs Subroutine
93 statements
Source File
private subroutine build_table_qr_acr_qs(rank, num_proc)
Uses
module_mp_tempo_params
build lookup table data for rain-snow collection
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: rank
integer, intent(in) :: num_proc
Calls
Called by
Call graph
build_table_qr_acr_qs calls mpi_allgather, mpi_barrier, mpi_wtime, gather, get_index_for_rank, initialize_arrays_qr_acr_qs, qr_acr_qs
gather calls mpi_gatherv
qr_acr_qs calls snow_moments
tempo_build_tables calls build_table_qr_acr_qs
build_tables calls tempo_build_tables