calc_gamma_cf – TEMPO Microphysics
calc_gamma_cf Function
29 statements
Source File
private function calc_gamma_cf(a, x) result(gamma_cf)
solves the normalized upper gamma function using a continued fractions method (modified Lentz Algorithm)
input: a = gamma function argument, x = lower limit of integration
output: normalized upper gamma function:
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: a
real(kind=wp), intent(in) :: x
Return Value real(kind=wp)
Called by
Call graph
calc_gamma_p calls calc_gamma_cf
qi_aut_qs calls calc_gamma_p
tempo_init calls qi_aut_qs
test_tempo_init calls tempo_init
run_tempo_tests calls test_tempo_init