compute_drop_evap – TEMPO Microphysics
compute_drop_evap Subroutine
28 statements
Source File
public subroutine compute_drop_evap()
Uses
module_mp_tempo_params
calculates droplet evaporation data
Arguments
None
Calls
Called by
Call graph
compute_drop_evap calls get_nuc
tempo_init calls compute_drop_evap
test_tempo_init calls tempo_init
run_tempo_tests calls test_tempo_init