create_bins – TEMPO Microphysics
create_bins Subroutine
21 statements
Source File
public subroutine create_bins(numbins, lowbin, highbin, bins, deltabins)
calculates log-spaced bins of hydrometer sizes to simplify calculations later
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: numbins
real(kind=dp), intent(in) :: lowbin
real(kind=dp), intent(in) :: highbin
real(kind=dp), intent(out), dimension(:) :: bins
real(kind=dp), intent(out), optional, dimension(:) :: deltabins
Called by
Call graph
initialize_bins_for_hail_size calls create_bins
initialize_bins_for_radar calls create_bins
initialize_bins_for_tables calls create_bins
tempo_build_tables calls initialize_bins_for_tables
tempo_init calls initialize_bins_for_hail_size, initialize_bins_for_radar, initialize_bins_for_tables
test_tempo_init calls tempo_init
build_tables calls tempo_build_tables
run_tempo_tests calls test_tempo_init