gather – TEMPO Microphysics
gather Subroutine
10 statements
Source File
private subroutine gather(local_flat, global_flat, sendcounts, displacements, ierror)
Uses
module_mp_tempo_params
wrapper to simplify MPI_Gatherv
Arguments
Type Intent Optional Attributes Name
real(kind=table_dp), intent(in), dimension(:) :: local_flat
real(kind=table_dp), intent(out), dimension(:) :: global_flat
integer, intent(in), dimension(:) :: sendcounts
integer, intent(in), dimension(:) :: displacements
integer, intent(inout) :: ierror
Calls
Called by
Call graph
gather calls mpi_gatherv
build_table_qr_acr_qg calls gather
build_table_qr_acr_qs calls gather
tempo_build_tables calls build_table_qr_acr_qg, build_table_qr_acr_qs
build_tables calls tempo_build_tables