get_version – TEMPO Microphysics
get_version Subroutine
17 statements
Source File
public subroutine get_version(version)
returns the tempo version string from the README.md file or returns empty string if not found
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(inout) :: version
Called by
Call graph
tempo_build_tables calls get_version
tempo_init calls get_version
test_tempo_init calls tempo_init
build_tables calls tempo_build_tables
run_tempo_tests calls test_tempo_init