initialize_arrays_qr_acr_qs – TEMPO Microphysics
initialize_arrays_qr_acr_qs Subroutine
18 statements
Source File
public subroutine initialize_arrays_qr_acr_qs(table_size)
initialize data arrays for rain-snow collection
Warning
twelve lookup table arrays are allocated and set here
Arguments
Type Intent Optional Attributes Name
integer, intent(out), optional :: table_size
Called by
Call graph
build_table_qr_acr_qs calls initialize_arrays_qr_acr_qs
tempo_init calls initialize_arrays_qr_acr_qs
tempo_build_tables calls build_table_qr_acr_qs
test_tempo_init calls tempo_init
build_tables calls tempo_build_tables
run_tempo_tests calls test_tempo_init