qr_acr_qs – TEMPO Microphysics
qr_acr_qs Subroutine
93 statements
Source File
private subroutine qr_acr_qs(local_start, local_end, ltcs_racs1, ltmr_racs1, ltcs_racs2, ltmr_racs2, ltcr_sacr1, ltms_sacr1, ltcr_sacr2, ltms_sacr2, ltnr_racs1, ltnr_racs2, ltnr_sacr1, ltnr_sacr2)
Uses
module_mp_tempo_params
calculates rain collecting snow (and inverse)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: local_start
integer, intent(in) :: local_end
real(kind=table_dp), intent(out), dimension(:,:,:,:) :: ltcs_racs1
real(kind=table_dp), intent(out), dimension(:,:,:,:) :: ltmr_racs1
real(kind=table_dp), intent(out), dimension(:,:,:,:) :: ltcs_racs2
real(kind=table_dp), intent(out), dimension(:,:,:,:) :: ltmr_racs2
real(kind=table_dp), intent(out), dimension(:,:,:,:) :: ltcr_sacr1
real(kind=table_dp), intent(out), dimension(:,:,:,:) :: ltms_sacr1
real(kind=table_dp), intent(out), dimension(:,:,:,:) :: ltcr_sacr2
real(kind=table_dp), intent(out), dimension(:,:,:,:) :: ltms_sacr2
real(kind=table_dp), intent(out), dimension(:,:,:,:) :: ltnr_racs1
real(kind=table_dp), intent(out), dimension(:,:,:,:) :: ltnr_racs2
real(kind=table_dp), intent(out), dimension(:,:,:,:) :: ltnr_sacr1
real(kind=table_dp), intent(out), dimension(:,:,:,:) :: ltnr_sacr2
Calls
Called by
Call graph
qr_acr_qs calls snow_moments
build_table_qr_acr_qs calls qr_acr_qs
tempo_build_tables calls build_table_qr_acr_qs
build_tables calls tempo_build_tables