rayleigh_soak_wetgraupel – TEMPO Microphysics
rayleigh_soak_wetgraupel Subroutine
56 statements
Source File
private subroutine rayleigh_soak_wetgraupel(x_g, a_geo, b_geo, fmelt, lambda_radar, meltratio_outside, m_w, m_i, backscatter)
calculates backscatter cross section of wet snow or graupel using Maxwell-Garnett mixing formula and Rayleigh approximation
original credit: Ulrich Blahak and G. Thompson
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: x_g
real(kind=dp), intent(in) :: a_geo
real(kind=dp), intent(in) :: b_geo
real(kind=dp), intent(in) :: fmelt
real(kind=dp), intent(in) :: lambda_radar
real(kind=dp), intent(in) :: meltratio_outside
complex(kind=dp), intent(in) :: m_w
complex(kind=dp), intent(in) :: m_i
real(kind=dp), intent(out) :: backscatter
Called by
Call graph
reflectivity_from_melting_graupel calls rayleigh_soak_wetgraupel
reflectivity_from_melting_snow calls rayleigh_soak_wetgraupel
reflectivity_10cm calls reflectivity_from_melting_graupel, reflectivity_from_melting_snow
tempo_main calls reflectivity_10cm
tempo_run calls tempo_main
test_cloud_number_aerosolaware calls tempo_run
test_cloud_number_ml calls tempo_run
test_cloud_number_non_aerosolaware calls tempo_run
test_graupel_sedimentation calls tempo_run
test_ml_cloud_effective_radius calls tempo_run
test_snow_sedimentation calls tempo_run
run_tempo_tests calls test_cloud_number_aerosolaware, test_cloud_number_ml, test_cloud_number_non_aerosolaware, test_graupel_sedimentation, test_ml_cloud_effective_radius, test_snow_sedimentation