reflectivity_10cm – TEMPO Microphysics
reflectivity_10cm Subroutine
45 statements
Source File
public subroutine reflectivity_10cm(refl10cm_from_melting_flag, temp, l_qr, rr, nr, ilamr, l_qs, rs, smoc, smob, smoz, l_qg, rg, ng, idx, ilamg, dbz)
Uses
module_mp_tempo_params
10-cm radar reflectivity
contributions from melting snow and graupel are optionally included
and
Arguments
Type Intent Optional Attributes Name
logical, intent(in) :: refl10cm_from_melting_flag
real(kind=wp), intent(in), dimension(:) :: temp
logical, intent(in), dimension(:) :: l_qr
real(kind=wp), intent(in), dimension(:) :: rr
real(kind=wp), intent(in), dimension(:) :: nr
real(kind=dp), intent(in), dimension(:) :: ilamr
logical, intent(in), dimension(:) :: l_qs
real(kind=wp), intent(in), dimension(:) :: rs
real(kind=dp), intent(in), dimension(:) :: smoc
real(kind=dp), intent(in), dimension(:) :: smob
real(kind=dp), intent(in), dimension(:) :: smoz
logical, intent(in), dimension(:) :: l_qg
real(kind=wp), intent(in), dimension(:) :: rg
real(kind=wp), intent(in), dimension(:) :: ng
integer, intent(in), dimension(:) :: idx
real(kind=dp), intent(in), dimension(:) :: ilamg
real(kind=wp), intent(out), dimension(:) :: dbz
Calls
Called by
Call graph
reflectivity_10cm calls find_melting_level, reflectivity_from_melting_graupel, reflectivity_from_melting_snow
reflectivity_from_melting_graupel calls complex_ice_maetzler, complex_water_ray, rayleigh_soak_wetgraupel
reflectivity_from_melting_snow calls complex_ice_maetzler, complex_water_ray, rayleigh_soak_wetgraupel
tempo_main calls reflectivity_10cm
tempo_run calls tempo_main
test_cloud_number_aerosolaware calls tempo_run
test_cloud_number_ml calls tempo_run
test_cloud_number_non_aerosolaware calls tempo_run
test_graupel_sedimentation calls tempo_run
test_ml_cloud_effective_radius calls tempo_run
test_snow_sedimentation calls tempo_run
run_tempo_tests calls test_cloud_number_aerosolaware, test_cloud_number_ml, test_cloud_number_non_aerosolaware, test_graupel_sedimentation, test_ml_cloud_effective_radius, test_snow_sedimentation