reflectivity_from_melting_snow – TEMPO Microphysics
reflectivity_from_melting_snow Function
39 statements
Source File
private function reflectivity_from_melting_snow(rs, smob, smoc, rr) result(ze_snow)
Uses
module_mp_tempo_params
calculates radar reflectivity from melting snow using binned approach
original credit: Ulrich Blahak and G. Thompson
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: rs
real(kind=dp), intent(in) :: smob
real(kind=dp), intent(in) :: smoc
real(kind=wp), intent(in) :: rr
Return Value real(kind=wp)
Calls
Called by
Call graph
reflectivity_from_melting_snow calls complex_ice_maetzler, complex_water_ray, rayleigh_soak_wetgraupel
reflectivity_10cm calls reflectivity_from_melting_snow
tempo_main calls reflectivity_10cm
tempo_run calls tempo_main
test_cloud_number_aerosolaware calls tempo_run
test_cloud_number_ml calls tempo_run
test_cloud_number_non_aerosolaware calls tempo_run
test_graupel_sedimentation calls tempo_run
test_ml_cloud_effective_radius calls tempo_run
test_snow_sedimentation calls tempo_run
run_tempo_tests calls test_cloud_number_aerosolaware, test_cloud_number_ml, test_cloud_number_non_aerosolaware, test_graupel_sedimentation, test_ml_cloud_effective_radius, test_snow_sedimentation