snow_moments – TEMPO Microphysics
snow_moments Subroutine
52 statements
Source File
public subroutine snow_moments(rs, tc, smob, smoc, ns, smo0, smo1, smo2, smoe, smof, smog, smoz)
Uses
module_mp_tempo_params
computes snow moments from Field et al. (2005)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: rs
real(kind=wp), intent(in) :: tc
real(kind=dp), intent(out) :: smob
real(kind=dp), intent(out) :: smoc
real(kind=dp), intent(out), optional :: ns
real(kind=dp), intent(out), optional :: smo0
real(kind=dp), intent(out), optional :: smo1
real(kind=dp), intent(out), optional :: smo2
real(kind=dp), intent(out), optional :: smoe
real(kind=dp), intent(out), optional :: smof
real(kind=dp), intent(out), optional :: smog
real(kind=dp), intent(out), optional :: smoz
Called by
Call graph
effective_radius calls snow_moments
qr_acr_qs calls snow_moments
tempo_main calls snow_moments, effective_radius
build_table_qr_acr_qs calls qr_acr_qs
tempo_run calls tempo_main
tempo_build_tables calls build_table_qr_acr_qs
test_cloud_number_aerosolaware calls tempo_run
test_cloud_number_ml calls tempo_run
test_cloud_number_non_aerosolaware calls tempo_run
test_graupel_sedimentation calls tempo_run
test_ml_cloud_effective_radius calls tempo_run
test_snow_sedimentation calls tempo_run
build_tables calls tempo_build_tables
run_tempo_tests calls test_cloud_number_aerosolaware, test_cloud_number_ml, test_cloud_number_non_aerosolaware, test_graupel_sedimentation, test_ml_cloud_effective_radius, test_snow_sedimentation