tempo_init – TEMPO Microphysics
tempo_init Subroutine
95 statements
Source File
public subroutine tempo_init(aerosolaware_flag, hailaware_flag, semi_sedi_flag, cloud_condensation_flag, refl10cm_from_melting_flag, ml_for_bl_nc_flag, ml_for_nc_flag, force_init_flag, tempo_cfgs)
Uses
module_mp_tempo_params
initialize tempo microphysics \section arg_table_tempo_init Argument Table \htmlinclude tempo_init.html
initialize tempo microphysics
Arguments
Type Intent Optional Attributes Name
logical, intent(in), optional :: aerosolaware_flag
logical, intent(in), optional :: hailaware_flag
logical, intent(in), optional :: semi_sedi_flag
logical, intent(in), optional :: cloud_condensation_flag
logical, intent(in), optional :: refl10cm_from_melting_flag
logical, intent(in), optional :: ml_for_bl_nc_flag
logical, intent(in), optional :: ml_for_nc_flag
logical, intent(in), optional :: force_init_flag
type(ty_tempo_cfgs), intent(inout) :: tempo_cfgs
Calls
Called by
Call graph
tempo_init calls compute_drop_evap, compute_efrw, compute_efsw, get_version, init_ml_data, initialize_array_efrw, initialize_array_efsw, initialize_arrays_ccn, initialize_arrays_drop_evap, initialize_arrays_freezewater, initialize_arrays_qi_aut_qs, initialize_arrays_qr_acr_qg, initialize_arrays_qr_acr_qs, initialize_bins_for_hail_size, initialize_bins_for_radar, initialize_bins_for_tables, initialize_graupel_vars, initialize_parameters, qi_aut_qs, read_table_ccn, read_table_freezewater, read_table_qr_acr_qg, read_table_qr_acr_qs
compute_drop_evap calls get_nuc
init_ml_data calls save_or_read_ml_data
initialize_bins_for_hail_size calls create_bins
initialize_bins_for_radar calls create_bins
initialize_bins_for_tables calls create_bins
qi_aut_qs calls calc_gamma_p
read_table_ccn calls check_before_table_read
read_table_freezewater calls check_before_table_read
read_table_qr_acr_qg calls check_before_table_read
read_table_qr_acr_qs calls check_before_table_read
calc_gamma_p calls calc_gamma_cf, calc_gamma_series
test_tempo_init calls tempo_init
run_tempo_tests calls test_tempo_init