test_tempo_init – TEMPO Microphysics
test_tempo_init Subroutine
3 statements
Source File
public subroutine test_tempo_init()
test tempo initialization procedure use ml_for_bl_nc_flag = .true. to initialize ml data which is used for a few tests test specific flags are then set in each test
Arguments
None
Calls
Called by
Call graph
test_tempo_init calls tempo_init
tempo_init calls compute_drop_evap, compute_efrw, compute_efsw, get_version, init_ml_data, initialize_array_efrw, initialize_array_efsw, initialize_arrays_ccn, initialize_arrays_drop_evap, initialize_arrays_freezewater, initialize_arrays_qi_aut_qs, initialize_arrays_qr_acr_qg, initialize_arrays_qr_acr_qs, initialize_bins_for_hail_size, initialize_bins_for_radar, initialize_bins_for_tables, initialize_graupel_vars, initialize_parameters, qi_aut_qs, read_table_ccn, read_table_freezewater, read_table_qr_acr_qg, read_table_qr_acr_qs
compute_drop_evap calls get_nuc
init_ml_data calls save_or_read_ml_data
initialize_bins_for_hail_size calls create_bins
initialize_bins_for_radar calls create_bins
initialize_bins_for_tables calls create_bins
qi_aut_qs calls calc_gamma_p
read_table_ccn calls check_before_table_read
read_table_freezewater calls check_before_table_read
read_table_qr_acr_qg calls check_before_table_read
read_table_qr_acr_qs calls check_before_table_read
calc_gamma_p calls calc_gamma_cf, calc_gamma_series
run_tempo_tests calls test_tempo_init