set( swan_src
${SRC}/swmod1.${EXTF}
${SRC}/swmod2.${EXTF}
${SRC}/SwanSpectPart.${EXTF}
${SRC}/m_constants.f90
${SRC}/m_fileio.f90
${SRC}/serv_xnl4v5.f90
${SRC}/mod_xnl4v5.f90
${SRC}/SwanGriddata.f90
${SRC}/SwanGridobjects.f90
${SRC}/SwanCompdata.f90
${SRC}/SdsBabanin.f90
${SRC}/SwanIEM.f90
${SRC}/SwanBraggScat.f90
${SRC}/SwanQCM.f90
${SRC}/swanpre1.${EXTF}
${SRC}/swanpre2.${EXTF}
${SRC}/swancom1.${EXTF}
${SRC}/swancom2.${EXTF}
${SRC}/swancom3.${EXTF}
${SRC}/swancom4.${EXTF}
${SRC}/swancom5.${EXTF}
${SRC}/swanout1.${EXTF}
${SRC}/swanout2.${EXTF}
${SRC}/swanser.${EXTF}
${SRC}/swanparll.${EXTF}
${SRC}/SwanReadGrid.f90
${SRC}/SwanReadADCGrid.f90
${SRC}/SwanReadTriangleGrid.f90
${SRC}/SwanReadEasymeshGrid.f90
${SRC}/SwanInitCompGrid.f90
${SRC}/SwanCheckGrid.f90
${SRC}/SwanCreateEdges.f90
${SRC}/SwanGridTopology.f90
${SRC}/SwanGridVert.f90
${SRC}/SwanGridCell.f90
${SRC}/SwanGridFace.f90
${SRC}/SwanPrintGridInfo.f90
${SRC}/SwanFindPoint.f90
${SRC}/SwanPointinMesh.f90
${SRC}/SwanBpntlist.f90
${SRC}/SwanPrepComp.f90
${SRC}/SwanVertlist.f90
${SRC}/SwanCompUnstruc.f90
${SRC}/SwanDispParm.f90
${SRC}/SwanPropvelX.f90
${SRC}/SwanSweepSel.f90
${SRC}/SwanPropvelS.f90
${SRC}/SwanTranspAc.f90
${SRC}/SwanTranspX.f90
${SRC}/SwanDiffPar.f90
${SRC}/SwanGSECorr.f90
${SRC}/SwanGradDepthorK.f90
${SRC}/SwanGradVel.f90
${SRC}/SwanInterpolatePoint.f90
${SRC}/SwanInterpolateAc.f90
${SRC}/SwanInterpolateOutput.f90
${SRC}/SwanConvAccur.f90
${SRC}/SwanConvStopc.f90
${SRC}/SwanThreadBounds.f90
${SRC}/SwanFindObstacles.f90
${SRC}/SwanCrossObstacle.f90
${SRC}/SwanComputeForce.f90
${SRC}/SwanIntgratSpc.f90
${SRC}/SwanBndStruc.f90
${SRC}/SwanReadfort18.f90
${SRC}/SwanPunCollect.f90
${SRC}/SwanSumOverNodes.f90
${SRC}/SwanMinOverNodes.f90
${SRC}/SwanMaxOverNodes.f90
${SRC}/SwanVTKWriteHeader.f90
${SRC}/SwanVTKWriteData.f90
${SRC}/SwanVTKPDataSets.f90
${SRC}/ocpids.${EXTF}
${SRC}/ocpcre.${EXTF}
${SRC}/ocpmix.${EXTF}
${SRC}/fftpack51.f90
${SRC}/swanpre3.${EXTF}
${SRC}/swpoint.${EXTF}
${SRC}/swan_iounits.${EXTF}
${SRC}/waves_control.${EXTF}
${SRC}/waves_coupler.${EXTF}
${SRC}/mod_swan_kinds.${EXTF}
${SRC}/swanmain.${EXTF}
)
