build_tables – TEMPO Microphysics
build_tables Program
20 statements
Source File
Uses
module_mp_tempo_tables
module_mp_tempo_params
mpi_f08
program to build 3 lookup tables for tempo microphysics
example build make build_tables -f Makefile.intel mpi=1
timing information (ursa) to build the largest lookup table (rain-graupel collection)
Description Time (s)
gfortran (-O2) 3000
mpif90 (-O2) 1 process 3000
mpif90 (-O2) 13 processes 250
ifort (-fp-model consistent) 1300
mpiifort (-fp-model consistent) 1 process 1300
mpiifort (-fp-model consistent) 13 processes 120
Calls
Variables
Type Attributes Name Initial
integer :: build_tables_rank
integer :: build_tables_num_proc
integer :: ierror
integer :: mpi_dp_size
Call graph
build_tables calls mpi_comm_rank, mpi_comm_size, mpi_finalize, mpi_init, mpi_type_size, tempo_build_tables
tempo_build_tables calls build_table_freezewater, build_table_qr_acr_qg, build_table_qr_acr_qs, get_version, initialize_bins_for_tables, initialize_graupel_vars, initialize_parameters, write_table_freezewater, write_table_qr_acr_qg, write_table_qr_acr_qs
build_table_freezewater calls freezewater, initialize_arrays_freezewater
build_table_qr_acr_qg calls mpi_allgather, mpi_barrier, mpi_wtime, gather, get_index_for_rank, initialize_arrays_qr_acr_qg, qr_acr_qg
build_table_qr_acr_qs calls mpi_allgather, mpi_barrier, mpi_wtime, gather, get_index_for_rank, initialize_arrays_qr_acr_qs, qr_acr_qs
initialize_bins_for_tables calls create_bins
gather calls mpi_gatherv
qr_acr_qs calls snow_moments